upcase_bin_DATA = \
	$(top_srcdir)/upcase/upcase-mandatory.txt	\
	$(top_srcdir)/upcase/upcase-null.txt		\
	$(top_srcdir)/upcase/upcase-recommended.txt

libexec_SCRIPTS = exfat-uctbl2bin.sh
upcase_bindir = $(docdir)

EXTRA_DIST = \
	exfat-uctbl2bin.sh \
	upcase-mandatory.txt \
	upcase-null.txt \
	upcase-recommended.txt
